# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-09 23:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('end_date', models.DateTimeField()),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('hash_field', models.TextField()),
                ('create_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('rating', models.IntegerField(default=0)),
                ('rating_img', models.TextField()),
                ('location', models.TextField()),
                ('img', models.TextField(default='')),
                ('url', models.TextField()),
                ('hash_field', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', models.TextField()),
                ('keep', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvote.Group')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvote.Restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='User_Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvote.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upvote', models.BooleanField(default=False)),
                ('downvote', models.BooleanField(default=False)),
                ('restaurant_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvote.Restaurant_Group')),
                ('user_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodvote.User_Group')),
            ],
        ),
    ]
