# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-22 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodvote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='group',
        ),
    ]
