# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-25 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodvote', '0002_remove_restaurant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='location',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='rating_img',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='url',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
