# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodvote', '0003_auto_20161025_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='search',
            field=models.TextField(default='ok'),
            preserve_default=False,
        ),
    ]
